// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"cosmosdb-demo/pkg/api"
	"cosmosdb-demo/pkg/handler"
	"cosmosdb-demo/pkg/repository"
	"cosmosdb-demo/pkg/service"
	"github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos"
)

// Injectors from wire.go:

func InitializeAPI(client *azcosmos.Client) *api.Server {
	repo := repository.NewRepo(client)
	hello := service.NewHelloService(repo)
	handlerApi := handler.NewHandler(hello)
	server := api.NewServer(handlerApi)
	return server
}
