// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"cosmosdb-demo/pkg/api"
	"cosmosdb-demo/pkg/handler"
	"cosmosdb-demo/pkg/repository"
	"cosmosdb-demo/pkg/service"
)

// Injectors from wire.go:

func InitializeAPI() *api.Server {
	repo := repository.NewRepo()
	hello := service.NewHelloService(repo)
	handlerApi := handler.NewHandler(hello)
	server := api.NewServer(handlerApi)
	return server
}
