// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"cosmosdb-demo/pkg/api"
	"cosmosdb-demo/pkg/handler"
	"cosmosdb-demo/pkg/logger"
	"cosmosdb-demo/pkg/repository"
	"cosmosdb-demo/pkg/service"
	"github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos"
)

// Injectors from wire.go:

func InitializeAPI(client *azcosmos.Client, log *logger.Logger) *api.Server {
	repo := repository.NewRepo(client, log)
	hello := service.NewHelloService(repo, log)
	handlerHandler := handler.NewHandler(hello, log)
	server := api.NewServer(handlerHandler)
	return server
}
