name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: go build -o api -v cmd/api
      - name: test coverage
        run: go test -v ./pkg/...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

